import LeanCordix.Global

/-!
# Cordix — Definition 60: iterator independence and recovery commutation

This module formalizes the iterator-level independence used by the global
metatheory:

* `Iterator.InTransformMonoid` — the transformation monoid `M(ι)` of an
  iterator: the monoid generated by the forward maps and yielded inverses of
  every iterator in `Reachable ι` (Definition 60, Eq. 54).
* `Iterator.Independent` — the two conditions of Definition 60 for a pair of
  iterators: all transformations commute, and neither's transformations
  disturb the step (inverse/continuation) the other yields.
* `Iterator.PairwiseIndependent` — a family of iterators is pairwise
  independent when distinct members are independent.

It also proves the state-level commutation lemma needed for Theorem 61:
under commutation of the relevant accumulated maps, `State.applyAcc` at `n`
commutes with `Step.psi` of a step acting on another fiber.
-/

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false

namespace Cordix

namespace Iterator

universe u v

variable {Γ : Type u} {E : Type v}

/-- **Definition 60 / Eq. (54), transformation monoid.** The monoid
`M(ι)` generated by the forward maps and the yielded inverses of every
iterator reachable from `ι`. -/
inductive InTransformMonoid (ι : Iterator Γ E) : (Γ → Γ) → Prop
  | id : InTransformMonoid ι id
  | fwd {ι' : Iterator Γ E} (h : Reachable ι ι') :
      InTransformMonoid ι (stepFwd ι')
  | inv {ι' : Iterator Γ E} (h : Reachable ι ι') (γ : Γ) :
      InTransformMonoid ι (stepInv ι' γ)
  | comp {f g : Γ → Γ} :
      InTransformMonoid ι f → InTransformMonoid ι g →
      InTransformMonoid ι (f ∘ g)

/-- The identity is in every transformation monoid. -/
theorem inTransformMonoid_id (ι : Iterator Γ E) : InTransformMonoid ι id :=
  InTransformMonoid.id

/-- **Definition 60 / Eq. (55).** Two iterators are independent when every
transformation of one commutes with every transformation of the other, and
neither's transformations disturb the step the other yields. -/
def Independent (ι₁ ι₂ : Iterator Γ E) : Prop :=
  (∀ {m₁ : Γ → Γ}, InTransformMonoid ι₁ m₁ → ∀ {m₂ : Γ → Γ},
      InTransformMonoid ι₂ m₂ → m₁ ∘ m₂ = m₂ ∘ m₁)
    ∧ (∀ {m₂ : Γ → Γ}, InTransformMonoid ι₂ m₂ → ∀ {ι₁' : Iterator Γ E},
        Reachable ι₁ ι₁' → ∀ γ, step ι₁' (m₂ γ) = step ι₁' γ)
    ∧ (∀ {m₁ : Γ → Γ}, InTransformMonoid ι₁ m₁ → ∀ {ι₂' : Iterator Γ E},
        Reachable ι₂ ι₂' → ∀ γ, step ι₂' (m₁ γ) = step ι₂' γ)

/-- A family of iterators is *pairwise independent* when any two distinct
members are independent. -/
def PairwiseIndependent {N : Type} (iters : N → Iterator Γ E) : Prop :=
  ∀ n m, n ≠ m → Independent (iters n) (iters m)

namespace Independent

/-- The commutation half of independence, packaged for use in recovery
exactness. -/
theorem comm {ι₁ ι₂ : Iterator Γ E} (h : Independent ι₁ ι₂)
    {m₁ m₂ : Γ → Γ} (hm₁ : InTransformMonoid ι₁ m₁)
    (hm₂ : InTransformMonoid ι₂ m₂) :
    m₁ ∘ m₂ = m₂ ∘ m₁ :=
  h.1 hm₁ hm₂

/-- Independence is symmetric. -/
theorem symm {ι₁ ι₂ : Iterator Γ E} (h : Independent ι₁ ι₂) :
    Independent ι₂ ι₁ := by
  rcases h with ⟨hcomm, h₂₁, h₁₂⟩
  exact ⟨fun {m₂} hm₂ {m₁} hm₁ => (@hcomm m₁ hm₁ m₂ hm₂).symm, h₁₂, h₂₁⟩

end Independent

end Iterator

namespace Full

universe u

variable {N K E : Type} [DecidableEq N] [DecidableEq K] {V : K → Type u}

/-- The accumulator carried by a fiber at a state; `id` when the fiber is
absent.  This is the state-level reading of the paper's `κ_n`. -/
def State.accAt (s : State N K E V) (n : N) : CoefCtx K V → CoefCtx K V :=
  match lookup s.reg n with
  | some f => Lifecycle.acc f.lc
  | none => id

/-- `accAt` reads the lifecycle accumulator of the fiber found in the
registry. -/
theorem State.accAt_eq {s : State N K E V} {n : N} {f : Fiber N K V E}
    (hf : lookup s.reg n = some f) :
    State.accAt s n = Lifecycle.acc f.lc := by
  simp [State.accAt, hf]

/-- `State.applyAcc` is exactly applying the fiber's accumulator to the
ambient context. -/
@[simp] theorem State.applyAcc_eq_accAt (s : State N K E V) (n : N) :
    State.applyAcc s n = ⟨s.reg, State.accAt s n s.ambient⟩ := by
  unfold State.applyAcc State.accAt
  cases h : lookup s.reg n with
  | none => rfl
  | some f =>
      cases hlc : f.lc with
      | inactive o => simp [State.applyAcc, State.accAt, h, hlc, Lifecycle.acc]
      | loading i κ v => simp [State.applyAcc, State.accAt, h, hlc, Lifecycle.acc]
      | active κ v => simp [State.applyAcc, State.accAt, h, hlc, Lifecycle.acc]
      | unloading κ v o => simp [State.applyAcc, State.accAt, h, hlc, Lifecycle.acc]

/-- `accAt` is unchanged by a registry update at a different name. -/
theorem State.accAt_set_ne {s : State N K E V} {n m : N} (hmn : n ≠ m)
    (g : Fiber N K V E) :
    State.accAt ⟨set s.reg m g, s.ambient⟩ n = State.accAt s n := by
  unfold State.accAt
  rw [lookup_set_ne s.reg m n g hmn]

/-- `State.applyAcc` commutes with `State.writeTable` at a different name. -/
theorem State.applyAcc_writeTable_commute {s : State N K E V} {n m : N}
    (hmn : n ≠ m) (δ : CoefCtx K V) :
    State.applyAcc (State.writeTable s m δ) n =
      State.writeTable (State.applyAcc s n) m δ := by
  unfold State.writeTable
  by_cases h : (lookup s.reg m).isSome
  · rcases Option.isSome_iff_exists.mp h with ⟨g, hg⟩
    simp [hg, State.applyAcc_eq_accAt, State.accAt_set_ne hmn]
  · have hm : lookup s.reg m = none := Option.not_isSome_iff_eq_none.mp h
    simp [hm, State.applyAcc_eq_accAt, State.accAt_set_ne hmn]

/-- **Theorem 61, step commutation.**  If a step acts on a fiber other than
`n`, then the ambient accumulator at `n` commutes with the step's `Ψ`,
provided the two accumulated maps commute.  This is the local form of the
paper's use of pairwise independence in the proof of Theorem 61. -/
theorem State.applyAcc_psi_commute {s : State N K E V} (st : Step s) {n : N}
    (hne : n ≠ st.name)
    (hcomm : ∀ {κn κm : CoefCtx K V → CoefCtx K V},
        State.accAt s n = κn →
        (∃ f, lookup s.reg st.name = some f ∧ Lifecycle.acc f.lc = κm) →
        κn ∘ κm = κm ∘ κn) :
    State.applyAcc (Step.psi st s) n = Step.psi st (State.applyAcc s n) := by
  cases st with
  | oInsert m c p hn hp hdisj => simp [Step.psi]
  | oRetire m f hf => simp [Step.psi]
  | oRemove m f o hf hl hchild => simp [Step.psi]
  | lBegin m f v hf hl ht => simp [Step.psi]
  | lIter m f ι κ v ι' δ h hreach hf hl ht hstep =>
      change State.applyAcc (State.writeTable s m δ) n =
        State.writeTable (State.applyAcc s n) m δ
      exact State.applyAcc_writeTable_commute hne δ
  | lFinish m f ι κ v δ h hreach hf hl ht hstep =>
      change State.applyAcc (State.writeTable s m δ) n =
        State.writeTable (State.applyAcc s n) m δ
      exact State.applyAcc_writeTable_commute hne δ
  | lRaise m f ι κ v e hreach hf hl hstep => simp [Step.psi]
  | lDivertAbort m f ι κ v hreach hf hl ht => simp [Step.psi]
  | lDivertLand m f ι κ v δ h c hreach hf hl ht hstep =>
      change State.applyAcc (State.writeTable s m δ) n =
        State.writeTable (State.applyAcc s n) m δ
      exact State.applyAcc_writeTable_commute hne δ
  | lLeave m f κ v hf hl ht => simp [Step.psi]
  | lUnload m f κ v o hf hl hg =>
      -- The step acts on `m`; `hne` says `n ≠ m`.
      have hcomm' : State.accAt s n ∘ κ = κ ∘ State.accAt s n := by
        exact hcomm (rfl) ⟨f, hf, by rw [hl]; rfl⟩
      have hacc_state : State.accAt { reg := s.reg, ambient := κ s.ambient } n =
          State.accAt s n := by
        rfl
      simp [Step.psi, State.applyAcc_eq_accAt, hne, hcomm', Function.comp, hacc_state]
      exact congrFun hcomm' s.ambient

/-- **Theorem 61, step commutation, iterator-independence form.**
If the component iterators of `n` and of the step's acting fiber are
independent, and the accumulated maps are in the corresponding
transformation monoids, then `State.applyAcc` at `n` commutes with the
step's `Ψ`. -/
theorem State.applyAcc_psi_commute_of_indep {s : State N K E V} (st : Step s)
    {n : N} (hne : n ≠ st.name)
    (iterOf : N → Iterator (CoefCtx K V) E)
    (hind : Iterator.Independent (iterOf n) (iterOf st.name))
    (hn_mem : Iterator.InTransformMonoid (iterOf n) (State.accAt s n))
    (hm_mem : ∀ f, lookup s.reg st.name = some f →
        Iterator.InTransformMonoid (iterOf st.name) (Lifecycle.acc f.lc)) :
    State.applyAcc (Step.psi st s) n = Step.psi st (State.applyAcc s n) := by
  refine State.applyAcc_psi_commute st hne ?_
  intro κn κm hκn hκm
  rcases hκm with ⟨f, hf, hκm_eq⟩
  have hn_mem' : Iterator.InTransformMonoid (iterOf n) κn := by
    simpa [hκn] using hn_mem
  have hm_mem' : Iterator.InTransformMonoid (iterOf st.name) κm := by
    have h := hm_mem f hf
    simpa [hκm_eq] using h
  exact hind.1 hn_mem' hm_mem'

/-- `tableAt` is insensitive to the order of `set` operations at distinct
names. -/
theorem State.tableAt_set_set_comm {r : Registry N K V E} {a : CoefCtx K V}
    {n m : N} (hmn : n ≠ m) (f g : Fiber N K V E) (x : N) :
    State.tableAt ⟨set (set r m g) n f, a⟩ x =
      State.tableAt ⟨set (set r n f) m g, a⟩ x := by
  by_cases hxn : x = n
  · subst x
    simp only [State.tableAt]
    rw [lookup_set_ne (set r n f) m n g hmn]
    simp
  · by_cases hxm : x = m
    · subst x
      simp only [State.tableAt]
      rw [lookup_set_ne (set r m g) n m f (Ne.symm hmn)]
      simp
    · simp only [State.tableAt]
      rw [lookup_set_ne (set r m g) n x f hxn]
      rw [lookup_set_ne r m x g hxm]
      rw [lookup_set_ne (set r n f) m x g hxm]
      rw [lookup_set_ne r n x f hxn]

/-- Full recovery commutes with a table write at a different name, up to
`≈`: the two operations touch distinct names. -/
theorem State.recoverAcc_writeTable_approx {s : State N K E V} {n m : N}
    (hmn : n ≠ m) (δ : CoefCtx K V) :
    State.Approx (State.recoverAcc (State.writeTable s m δ) n)
      (State.writeTable (State.recoverAcc s n) m δ) := by
  constructor
  · rw [State.recoverAcc_writeTable_ambient hmn δ]
    cases h : lookup (State.recoverAcc s n).reg m <;> simp [State.writeTable, h]
  · intro x
    by_cases hn : (lookup s.reg n).isSome
    · rcases Option.isSome_iff_exists.mp hn with ⟨f, hf⟩
      by_cases hm : (lookup s.reg m).isSome
      · rcases Option.isSome_iff_exists.mp hm with ⟨g, hg⟩
        cases hlc : f.lc with
        | inactive o =>
            simp [State.recoverAcc, State.writeTable, hf, hlc, hg, lookup_set_ne, hmn]
        | loading i κ v =>
            have hf' : lookup (set s.reg m { g with table := δ }) n = some f := by
              rw [lookup_set_ne s.reg m n ({ g with table := δ }) hmn]
              exact hf
            rw [State.writeTable_eq_of_lookup hg]
            rw [State.recoverAcc_eq_of_lookup hf']
            have hg' : lookup (State.recoverAcc s n).reg m = some g := by
              rw [State.lookup_recoverAcc_ne hmn]
              exact hg
            rw [State.writeTable_eq_of_lookup hg']
            rw [State.recoverAcc_eq_of_lookup hf]
            simp [hlc]
            exact State.tableAt_set_set_comm hmn
              { f with table := κ f.table, lc := Lifecycle.loading i κ v }
              { g with table := δ } x
        | active κ v =>
            have hf' : lookup (set s.reg m { g with table := δ }) n = some f := by
              rw [lookup_set_ne s.reg m n ({ g with table := δ }) hmn]
              exact hf
            rw [State.writeTable_eq_of_lookup hg]
            rw [State.recoverAcc_eq_of_lookup hf']
            have hg' : lookup (State.recoverAcc s n).reg m = some g := by
              rw [State.lookup_recoverAcc_ne hmn]
              exact hg
            rw [State.writeTable_eq_of_lookup hg']
            rw [State.recoverAcc_eq_of_lookup hf]
            simp [hlc]
            exact State.tableAt_set_set_comm hmn
              { f with table := κ f.table, lc := Lifecycle.active κ v }
              { g with table := δ } x
        | unloading κ v o =>
            have hf' : lookup (set s.reg m { g with table := δ }) n = some f := by
              rw [lookup_set_ne s.reg m n ({ g with table := δ }) hmn]
              exact hf
            rw [State.writeTable_eq_of_lookup hg]
            rw [State.recoverAcc_eq_of_lookup hf']
            have hg' : lookup (State.recoverAcc s n).reg m = some g := by
              rw [State.lookup_recoverAcc_ne hmn]
              exact hg
            rw [State.writeTable_eq_of_lookup hg']
            rw [State.recoverAcc_eq_of_lookup hf]
            simp [hlc]
            exact State.tableAt_set_set_comm hmn
              { f with table := κ f.table, lc := Lifecycle.unloading κ v o }
              { g with table := δ } x
      · have hm' : lookup s.reg m = none := Option.not_isSome_iff_eq_none.mp hm
        cases hlc : f.lc <;>
          simp [State.recoverAcc, State.writeTable, hf, hlc, hm', lookup_set_ne, hmn,
            Ne.symm hmn]
    · have hn' : lookup s.reg n = none := Option.not_isSome_iff_eq_none.mp hn
      by_cases hm : (lookup s.reg m).isSome
      · rcases Option.isSome_iff_exists.mp hm with ⟨g, hg⟩
        simp [State.recoverAcc, State.writeTable, hn', hg, lookup_set_ne, hmn]
      · have hm' : lookup s.reg m = none := Option.not_isSome_iff_eq_none.mp hm
        simp [State.recoverAcc, State.writeTable, hn', hm']

/-- Full recovery commutes with a step acting on another fiber, up to `≈`.
This is the `State.recoverAcc` analogue of `State.applyAcc_psi_commute` and
the local engine of Theorem 61 once the tracked fiber may have written its
own table. -/
theorem State.recoverAcc_psi_commute_approx {s : State N K E V} (st : Step s)
    {n : N} (hne : n ≠ st.name)
    (hcomm : ∀ {κn κm : CoefCtx K V → CoefCtx K V},
        State.accAt s n = κn →
        (∃ f, lookup s.reg st.name = some f ∧ Lifecycle.acc f.lc = κm) →
        κn ∘ κm = κm ∘ κn) :
    State.Approx (State.recoverAcc (Step.psi st s) n)
      (Step.psi st (State.recoverAcc s n)) := by
  cases st with
  | oInsert m c p hn hp hdisj => simpa [Step.psi] using State.Approx.refl (State.recoverAcc s n)
  | oRetire m f hf => simpa [Step.psi] using State.Approx.refl (State.recoverAcc s n)
  | oRemove m f o hf hl hchild => simpa [Step.psi] using State.Approx.refl (State.recoverAcc s n)
  | lBegin m f v hf hl ht => simpa [Step.psi] using State.Approx.refl (State.recoverAcc s n)
  | lIter m f ι κ v ι' δ h hreach hf hl ht hstep =>
      change State.Approx (State.recoverAcc (State.writeTable s m δ) n)
        (State.writeTable (State.recoverAcc s n) m δ)
      exact State.recoverAcc_writeTable_approx hne δ
  | lFinish m f ι κ v δ h hreach hf hl ht hstep =>
      change State.Approx (State.recoverAcc (State.writeTable s m δ) n)
        (State.writeTable (State.recoverAcc s n) m δ)
      exact State.recoverAcc_writeTable_approx hne δ
  | lRaise m f ι κ v e hreach hf hl hstep => simpa [Step.psi] using State.Approx.refl (State.recoverAcc s n)
  | lDivertAbort m f ι κ v hreach hf hl ht => simpa [Step.psi] using State.Approx.refl (State.recoverAcc s n)
  | lDivertLand m f ι κ v δ h c hreach hf hl ht hstep =>
      change State.Approx (State.recoverAcc (State.writeTable s m δ) n)
        (State.writeTable (State.recoverAcc s n) m δ)
      exact State.recoverAcc_writeTable_approx hne δ
  | lLeave m f κ v hf hl ht => simpa [Step.psi] using State.Approx.refl (State.recoverAcc s n)
  | lUnload m f κ v o hf hl hg =>
      have hcomm' : State.accAt s n ∘ κ = κ ∘ State.accAt s n := by
        exact hcomm (rfl) ⟨f, hf, by rw [hl]; rfl⟩
      by_cases hn : (lookup s.reg n).isSome
      · rcases Option.isSome_iff_exists.mp hn with ⟨fn, hfn⟩
        cases hlc : fn.lc with
        | inactive o =>
            constructor <;>
              simp [Step.psi, State.recoverAcc, hfn, hlc, hne]
        | loading i κn vn =>
            constructor
            · have haccn : State.accAt s n = κn := by
                simp [State.accAt_eq hfn, hlc, Lifecycle.acc]
              simp [Step.psi, State.recoverAcc, hfn, hlc, hne]
              exact congrFun (by simpa [haccn] using hcomm') s.ambient
            · intro x
              simp [Step.psi, State.recoverAcc, hfn, hlc, hne]
              rfl
        | active κn vn =>
            constructor
            · have haccn : State.accAt s n = κn := by
                simp [State.accAt_eq hfn, hlc, Lifecycle.acc]
              simp [Step.psi, State.recoverAcc, hfn, hlc, hne]
              exact congrFun (by simpa [haccn] using hcomm') s.ambient
            · intro x
              simp [Step.psi, State.recoverAcc, hfn, hlc, hne]
              rfl
        | unloading κn vn on =>
            constructor
            · have haccn : State.accAt s n = κn := by
                simp [State.accAt_eq hfn, hlc, Lifecycle.acc]
              simp [Step.psi, State.recoverAcc, hfn, hlc, hne]
              exact congrFun (by simpa [haccn] using hcomm') s.ambient
            · intro x
              simp [Step.psi, State.recoverAcc, hfn, hlc, hne]
              rfl
      · have hn' : lookup s.reg n = none := Option.not_isSome_iff_eq_none.mp hn
        constructor <;> simp [Step.psi, State.recoverAcc, hn', hne]

/-- **Theorem 61, step commutation, full-recovery form.**  If the component
iterators of `n` and of the step's acting fiber are independent and the
accumulated maps lie in the corresponding transformation monoids, then full
recovery at `n` commutes with the step's `Ψ` up to `≈`. -/
theorem State.recoverAcc_psi_commute_approx_of_indep {s : State N K E V}
    (st : Step s) {n : N} (hne : n ≠ st.name)
    (iterOf : N → Iterator (CoefCtx K V) E)
    (hind : Iterator.Independent (iterOf n) (iterOf st.name))
    (hn_mem : Iterator.InTransformMonoid (iterOf n) (State.accAt s n))
    (hm_mem : ∀ f, lookup s.reg st.name = some f →
        Iterator.InTransformMonoid (iterOf st.name) (Lifecycle.acc f.lc)) :
    State.Approx (State.recoverAcc (Step.psi st s) n)
      (Step.psi st (State.recoverAcc s n)) := by
  refine State.recoverAcc_psi_commute_approx st hne ?_
  intro κn κm hκn hκm
  rcases hκm with ⟨f, hf, hκm_eq⟩
  have hn_mem' : Iterator.InTransformMonoid (iterOf n) κn := by
    simpa [hκn] using hn_mem
  have hm_mem' : Iterator.InTransformMonoid (iterOf st.name) κm := by
    have h := hm_mem f hf
    simpa [hκm_eq] using h
  exact hind.1 hn_mem' hm_mem'

end Full

end Cordix
